### ISSUE TITLE
change b element to span for menu caret

### ISSUE THREAD

**Issue by jongund** [paypal/skipto#33]
<b class="caret">

to

<span class="caret">

**Comment by blrichwine** [comment]
I'm curious if there is any activity on this. I promote using PayPal's skipNav plug-in, however this seemingly random use of the b element causes accessibility tools to promote errors or warnings.

I hosted my own copy locally, and there seems to be no ill effect in changing the b element to a span. 

For example, change this:
<a accesskey="0" tabindex="0" data-wrap="true" class="dropMenu-toggle skipTo onfocus " id="drop4" role="button" aria-haspopup="true" aria-expanded="false" data-toggle="dropMenu" href="#" data-target="menu1">Skip To...<b class="caret"></b></a>

to this:
<a accesskey="0" tabindex="0" data-wrap="true" class="dropMenu-toggle skipTo onfocus " id="drop4" role="button" aria-haspopup="true" aria-expanded="false" data-toggle="dropMenu" href="#" data-target="menu1">Skip To...<span class="caret"></span></a>

I know from an accessibility stand point, it seems minor. However, I have site owners that are refusing to use the plug-in due to the flags automatic tools are producing on the plug-in's code.

Thanks!
  Brian

**Comment by mpnkhan** [comment]
Hi @blrichwine 
Thanks for promting skipNav plugin. As you said, changing b element to span do not have problems as the css is based on class. 
Changes b element to span. https://github.com/paypal/skipto/commit/37c3c38d53b94eedb5f7d2a3bc6599fa8e90f92d

Thanks

**Comment by jongund** [comment]
Thank you.

Jon

**Comment by blrichwine** [comment]
Thank you!!
